name: Move oreui-main to root

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean repo (keep folder + workflow)
        run: |
          shopt -s extglob
          rm -rf !(oreui-main|.github)

      - name: Move oreui-main contents to root
        run: |
          shopt -s dotglob
          mv oreui-main/* .

      - name: Cleanup
        run: |
          rm -rf oreui-main
          rm -rf .github

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Move oreui-main to root + self-destruct" || echo "No changes"
          git push
